# ec2-configure.yml

---
  - name: Configure the Webservers
    hosts: webservers
    become: yes
    gather_facts: no
    tasks:
      - name: Install Python
        yum:
          name: "{{ item }}"
          state: latest
        loop:
          - python3
          - python3-pip.noarch
          - python-virtualenv.noarch
          - python3-setuptools.noarch
      - name: Install Pip
        shell: |
          curl -O https://bootstrap.pypa.io/get-pip.py
          python3 get-pip.py --user
      - name: Install Boto3
        pip:
          name: "{{ item }}"
          state: latest
          executable: pip3
          virtualenv_command: /usr/bin/python3 -m venv
        loop:
          - boto
      - name: Install Apache2
        yum: 
          name: "{{ item }}"
          state: latest
        loop:
          - httpd
          - httpd-tools
      - name: Start and Enable Apache2
        systemd:
          name: httpd
          state: started
          enabled: yes
      - name: configure index.html
        shell: |
          echo "Hello World from $(hostname -f)" > /var/www/html/index.html