# ec2-configure.yml

---
  - name: Configure the Webservers
    hosts: all
    #become: yes
    remote_user: ec2-user
    connection: ssh
    gather_facts: no
    roles: 
      - python
      - apache